config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'

  resources :articles

  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  
  resources :categories, except: [:destroy]
  
  get 'about', to: 'pages#about'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :content, presence: true, length: {minimum: 300}

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :articles, dependent: :destroy

  validates :username, presence: true,
                    uniqueness: {case_sensitive: false},
                    length: {minimum: 3, maximum: 25}

  VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
                    uniqueness: {case_sensitive: false},
                    length: {maximum: 105},
                    format: {with: VALID_EMAIL}

  before_save {self.email = self.email.downcase}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :nav_categories, :current_user, :logged_in?, :require_user, :admin_or_same_user
  
  def nav_categories
    Category.all
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must log in first."
      redirect_to login_path
    end
  end

  def admin_or_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'Unauthorized Action'
      redirect_to user_path(current_user)
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only:[:show, :edit, :update, :destroy]
  before_action :set_user, except:[:index, :new, :create]
  before_action :require_user, except:[:show, :index]
  before_action :admin_or_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.all.paginate(page: params[:page], per_page: 3)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully.'
      redirect_to user_path(@article.user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = 'Article was updated successfully.'
      redirect_to user_path(@article.user)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_user
    @user = @article.user
  end

  def article_params
    params.require(:article).permit(:title, :content, category_ids: [])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "The #{@category.name} category has been created."
      redirect_to new_category_path
    else
      render "new"
    end
  end

  def index
    @categories = Category.all
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "This category is now called #{@category.name}."
      redirect_to @category
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Unauthorized Action."
      redirect_to categories_path
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to user_path(current_user) if logged_in?
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.username}!"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Come back soon!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update, :destroy]
  before_action :admin_or_same_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end
  
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thanks, #{@user.username}! We can't wait to see what you write."
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account has been updated."
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Your account and all your articles have been deleted."
      redirect_to root_path
  end
  
  private

  def user_params
    params.require(:user). permit(:username, :email, :password, :bio)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "profile-pic")
  end

  def edit_button
    if logged_in? && (@user == current_user || current_user.admin?)
      link_to 'Edit', edit_article_path, class: "btn btn-orange float-left ml-5 my-3"
    end
  end

  def delete_button
    if logged_in? && (@user == current_user || current_user.admin?)
      link_to 'Delete', article_path, class: "btn btn-red float-right mr-5 my-3", method: :delete, data: {confirm: "Are you sure?"}
    end
  end

end

app/views/articles/_article.html.erb
<div class="card card-articles text-center mt-3 mb-4 justify-content-md-center">
  <div class="card-header pb-1 pt-3">
    <h2 class="mb-1"><%= link_to article.title, article, class: "link-white title" %></h2>
    <h6><%= time_ago_in_words(article.created_at) %> ago</h6>
    <h3><%= render article.categories %></h3>
  </div>
  <div class="card-body text">
    <h6 class="card-title font-italic">by <%= link_to (gravatar_for article.user, size: 35), article.user %> <%= link_to article.user.username, article.user, class: "link-blue" %></h6>
    <%= simple_format(truncate(article.content, length: 370), class: 'card-text') %>
  </div> 
  <div class="card-footer">
  </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row justify-content-center">
  <div class="col-10">
    <%= form_with model: @article, local: true do |f| %>

      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :content, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_area :content, rows: 8, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :category, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "('Command' or 'Windows' + click to make multiple selections)" }, { multiple: true, size: 3, class: "custom-select" }) %>
        </div>
      </div>

      <div class="form-group row justify-content-center mt-4">
        <%= f.submit class: "btn btn-green" %>
        <%= link_to 'Cancel & Return to Home', user_path(current_user), class: "btn btn-brown"%>
      </div>

    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="jumbotron bg bg-edit col-10">
  <%= render 'layouts/msgs' %>
  <h1 class="text-center mt-2 mb-4 display-5 title">Edit Your Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<%= render "layouts/enjoy_more" %>
<%= render 'layouts/msgs' %>
<%= will_paginate @articles, class: "apple_pagination mb-1" %>
<% @articles.each do |article| %>
  <%= render article %>
<% end %>
<%= will_paginate @articles, class: "apple_pagination mb-1" %>
<%= render "layouts/enjoy_more" %>

app/views/articles/new.html.erb
<div class="jumbotron bg bg-create col-10">
  <%= render 'layouts/msgs' %>
  <h1 class="text-center mt-2 mb-4 display-5 title">Create an Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<%= render "layouts/enjoy_more" %>
<%= render 'layouts/msgs' %>
<div class="card card-articles text-center mt-3 mb-4">
  <div class="card-header pb-2 pt-3">
    <%= edit_button %>
    <%= delete_button %>
    <h1 class= "title mb-1"><%= @article.title %></h1>
    <h6><%= time_ago_in_words(@article.created_at) %> ago</h6>
    <h3><%= render @article.categories %></h3>
  </div>
  <div class="card-body text">
    <h6 class="card-title font-italic mt-2 mb-4">by <%= link_to (gravatar_for @user, size: 35), @user %> <%= link_to @user.username, @user, class: "link-blue" %></h6>
    <%= simple_format(@article.content) %>
  </div> 
  <div class="card-footer">
    <%= edit_button %>
    <%= delete_button %>
  </div>
</div>
<%= render "layouts/enjoy_more" %>

app/views/categories/_category.html.erb
<span class="badge badge-pill badge-light link-blue mt-2 mb-1 py-2"><%= link_to category.name, category_path(category), class: "link-blue" %></span>&nbsp;

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<div class="row justify-content-center">
  <div class="col-10">
    <%= form_with model: @category, local: true do |f| %>

      <div class="form-group row">
        <%= f.label :name, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row justify-content-center mt-4">
        <%= f.submit class: "btn btn-green" %>
        <%= link_to 'Cancel & Return to Home', root_path, class: "btn btn-brown" %>
      </div>

    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="jumbotron bg bg-no-pic col-10">
  <%= render 'layouts/msgs' %>
  <h1 class="text-center mt-2 mb-4 display-5 title">Edit Category</h1>
  <%= render 'form' %>
</div>

app/views/categories/new.html.erb
<div class="jumbotron bg bg-no-pic col-10">
  <%= render 'layouts/msgs' %>
  <h1 class="text-center mt-2 mb-4 display-5 title">Create a New Category</h1>
  <%= render 'shared/errors', obj: @category %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with model: @category, local: true do |f| %>

        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row justify-content-center mt-4">
          <%= f.submit class: "btn btn-green" %>
          <%= link_to 'Cancel & Return to Home', root_path, class: "btn btn-brown" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<%= render "layouts/enjoy_more" %>
<%= render 'layouts/msgs' %>
<div class="jumbotron bg bg-no-pic col-10 my-4">
  <% if logged_in? && (@user == current_user || current_user.admin?) %>
    <%= link_to 'Edit', edit_category_path, class: "btn btn-orange float-left ml-5 my-3" %>
  <% end %>
  <% if logged_in? && (@user == current_user || current_user.admin?) %>
    <%= link_to 'Delete', article_path, class: "btn btn-red float-right mr-5 my-3", method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
  <h1 class= "text-center display-4 title"><%= @category.name %></h1>
</div>
<% will_paginate @category_articles, class: "apple_pagination mb-1" %>
<%= render @category.articles %>
<% will_paginate @category_articles, class: "apple_pagination mb-1" %>
<%= render "layouts/enjoy_more" %>

app/views/layouts/_enjoy_more.html.erb
<% if !logged_in? %>
  <div class="jumbotron text-center col-10 mt-3 mb-4" id="jumbotron-home">
    <h1 class="display-4 title">Enjoy More Lovely!</h1>
    <br/>
    <p class="lead text">Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
    <br/>
    <%= render "layouts/signup_login" %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <footer class="py-2">
    <div class="text-center">
      <small>Copyright &copy; <%= Time.now.year %> Scott Hoisington </small>
    </div>
  </footer>
  

app/views/layouts/_msgs.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg px-4">
  
  <%= link_to "LovelyBlog", root_path, class: "link-blue my-1 mr-5", id: "logo" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item active">
          <%= link_to current_user.username + (current_user.admin? ? " (Admin)" : ""), user_path(current_user), class: "nav-link link-black mr-4" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Log Out", logout_path, method: :delete, class: "nav-link link-black" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Write", new_article_path, class: "nav-link link-black" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Log In", login_path, class: "nav-link link-black" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign Up", signup_path, class: "nav-link link-black mr-4" %>
        </li>
      <% end %>
      <li class="nav-item active">
        <%= link_to "Articles", articles_path, class: "nav-link link-black" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle link-black" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "New Category", new_category_path, class: "dropdown-item link-black" %>
            <div class="dropdown-divider"></div>
          <% end %>
          <% nav_categories.each do |cat| %>
            <%= link_to cat.name, category_path(cat), class: "dropdown-item link-black" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item active">
        <%= link_to "Bloggers", users_path, class: "nav-link link-black" %>
      </li>
      <li class="nav-item active">
        <%= link_to "About", about_path, class: "nav-link link-black" %>
      </li>
    </ul>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" aria-label="Search">
      <button class="btn btn-blue my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_signup_login.html.erb
<% if !logged_in? %>
  <%= link_to "Sign Up", signup_path, class: "btn btn-lg btn-green" %>
  <%= link_to "Log In", login_path, class: "btn btn-lg btn-green" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>LovelyBlog</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'layouts/nav' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
  
</html>

app/views/pages/about.html.erb
<div class="jumbotron text-center col-10 justify-content-center" id="jumbotron-about">
  <%= render 'layouts/msgs' %>
  <h1 class="display-4 title">About Us</h1>
  <br/>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ex delectus itaque eius suscipit. Praesentium sed obcaecati ab! Voluptates, harum, illo officiis repellendus fugit ullam provident incidunt aliquam voluptatum libero mollitia? Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus eaque, expedita suscipit hic, eos fugiat est facere ut, nam ullam odio nobis doloremque voluptatem quo nostrum libero praesentium iste? Cupiditate. Suscipit nulla facere veritatis commodi at perspiciatis!</p>
  <br/>
  <%= render "layouts/signup_login" %>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center col-10" id="jumbotron-home">
  <%= render 'layouts/msgs' %>
  <h1 class="display-4 title">Celebrate Lovely!</h1>
  <br/>
  <p class="lead text">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellendus enim nihil voluptates recusandae voluptatem ad, unde commodi at perspiciatis!</p>
  <br/>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit.</p>
  <br/>
  <%= render "layouts/signup_login" %>
</div>

app/views/shared/_errors.html.erb
<% if obj && obj.errors.any? %>
  <div class="alert alert-danger col-10 alert-dismissible fade show" role="alert">
    <% if obj == @article %>
      <h5 class="alert-heading">The following errors prevented your article from being saved:</h5>
    <% elsif obj == @user %>
      <h5 class="alert-heading">The following errors prevented your account from being created:</h5>
    <% else %>
      <h5 class="alert-heading">The following errors occurred:</h5>
    <% end %>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row justify-content-center">
  <div class="col-10">
    <%= form_with model: @user, local: true do |f| %>

      <div class="form-group row">
        <%= f.label :username, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_field :username, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :email, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :password, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :bio, class: "col-2 col-form-label" %>
        <div class="col-10">
          <%= f.text_area :bio, class: "form-control" %>
        </div>
      </div>

      <div class="form-group row justify-content-center mt-4">
        <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-green") %>
        <%= link_to 'Cancel & Return to Home', root_path, class: "btn btn-brown" %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="jumbotron bg bg-create col-10">
  <%= render 'layouts/msgs' %>
  <h1 class="text-center mt-2 mb-4 display-5 title">Edit Your Profile</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<%= render "layouts/enjoy_more" %>
<%= render 'layouts/msgs' %>
<%= will_paginate @users, class: "apple_pagination mb-2" %>
<% @users.each do |user| %>
  <div class="jumbotron bg-create col-7 mt-3 mb-3">
    <%= link_to (gravatar_for user, size: 200), user, class: "float-left", id: "special" %>
    <div>
      <h1 class="text-center mt-3 title"><%= link_to user.username, user, class: "link-white" %></h1>
      <h6 class="text-center mt-2 mb-4"><%= user.email %></h6>
      <h4 class="text-center mt-2 mb-2"><%= pluralize(user.articles.count, "Article") %></h4>
      <h5 class="text-center mt-2 mb-3"><i>Joined <%= time_ago_in_words(user.created_at) %> ago</i></h5>
      <br/><br/>
      <p><%= user.bio %></p>
    </div>
  </div>
<% end %>
<%= will_paginate @users, class: "apple_pagination" %>
<%= render "layouts/enjoy_more" %>

app/views/users/new.html.erb
<div class="jumbotron bg bg-no-pic col-10">
  <%= render 'layouts/msgs' %>
  <h1 class="text-center mt-2 mb-4 display-5 title">Sign Up</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<%= render "layouts/enjoy_more" %>
<div class="jumbotron bg-create col-8 mt-3 mb-4">
  <%= render 'layouts/msgs' %>
  <div class="text-center">
    <div>
      <% if logged_in? && @user == current_user %>
        <%= link_to 'Edit Profile', edit_user_path(current_user), class: "btn btn-orange mx-3 mb-4" %>
      <% end %>
      <% if logged_in? && (@user == current_user || current_user.admin?) %>
        <%= link_to 'Delete Account', user_path(current_user), class: "btn btn-red mx-3 mb-4", method: :delete, data: {confirm: "This will also delete all articles and cannot be undone! Are you sure?"} %>
      <% end %>
    </div><br/>
    <div id="special" class="float-left">
      <%= gravatar_for @user, size: 200 %>
    </div>
    <div>
      <h1 class="text-center mt-3 title"><%= @user.username %></h1>
      <h6 class="text-center mt-2 mb-4"><%= @user.email %></h6>
      <h4 class="text-center mt-2 mb-2"><%= pluralize(@articles.count, "Article") %></h4>
      <h5 class="text-center mt-2 mb-3"><i>Joined <%= time_ago_in_words(@user.created_at) %> ago</i></h5>
    </div>
  </div>
  <br/><br/>
  <p><%= @user.bio %></p>
</div>

<%= will_paginate @articles, class: "apple_pagination mb-1" %>
<% @articles.each do |article| %>
  <%= render article %>
<% end %>
<%= will_paginate @articles, class: "apple_pagination mb-1" %>
<%= render "layouts/enjoy_more" %>